Online Trim Estimation and "Double Lane Fitting" with least squares
duckietown/docs-learning_materials pull request #8
Opened 2019-12-19 18:50 UTC by CharlesCossette

2019-12-30 12:30 UTC, bhairavmehta95 commented
@CharlesCossette sorry, we never saw this (@ + pinging works). 

@maivincent @liampaull

2019-12-30 12:31 UTC, bhairavmehta95 requested changes

2019-12-30 12:31 UTC, bhairavmehta95 commented on book/learning_materials/80_advanced_perception/70_gaussian_processes.md
> +training set points that were `too far away' from the vehicle.  In practice,
you've got a misformatted ` instead of '

2019-12-30 12:31 UTC, bhairavmehta95 commented on book/learning_materials/80_advanced_perception/70_gaussian_processes.md
> +## Gaussian process regression for lane modeling {#gaussian_processes status=beta}
Is this ready? you can switch to `status=ready`

2019-12-30 12:31 UTC, bhairavmehta95 commented on book/learning_materials/75_control/40_trim_estimation.md
> +In this section, a solution is proposed to specifically address the issue with a badly calibrated ``trim''. That is, generating the ability to dynamically adjust for an incorrect trim calibration onl
You've got the same issue here (`` + ''). Tbh, not sure which one it's supposed to be?

2020-04-17 02:58 UTC, liampaull commented
I (or someone) should evaluate and determine whether this should be merged into daffy somewhere

2022-10-19 15:47 UTC, closed without merging